apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage
  nfs:
    path: /home/opt/nfs
    server: 192.168.100.167
